### ISSUE TITLE
[Feat] 모델 분석 결과화면 구현

### ISSUE THREAD

**Issue by seunghee17** [soulive-A/Android#2]
**Issue**
- 이슈 내용: 모델 분석 결과화면 기능 구현

**Branch Name**
- 생성 브랜치 이름 : `feat/model_result`

**To-Do List**
- [x] 모델 분석 결과화면 탭1 ui구현
- [x] 모델 분석 결과화면 탭2 ui구현
- [x] 모델 분석 결과화면 탭3 ui구현
- [x] 모델 분석 결과화면 탭4 ui구현
- [x] api연동(확정 나면 더 투두 구체화하기)
